name: Selenium TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu GitHub reposundan çek
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Java'yı kur
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      # 3. Maven'i cache'e al (build performansını hızlandırmak için)
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Maven testleri çalıştır
      - name: Run Selenium TestNG Tests
        run: mvn clean test
